@EFCoreMultiTenancy_HostAddress = http://localhost:5021
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRJZCI6InRlbmFudEEifQ.w1chUb4GxHSjVzFrmcWifihmUyeodkjR6F9nYAbZ2ks

### Criar produto
POST {{EFCoreMultiTenancy_HostAddress}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Notebook-tenantA",
  "price": 4999.99
}

###

### Listar produtos
GET {{EFCoreMultiTenancy_HostAddress}}/products
Authorization: Bearer {{token}}

###
